# -*- coding: utf-8 -*-
"""Text generation code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1br7eMwVNFaLHzq73UIkWfwvFPwwDJm
"""

! pip install transformers torch

from transformers import pipeline
#upload text generation model (Gen AI)
generator=pipeline ("text-generation", model="gpt2")
#input prompt
prompt="Artificial Intelligence in finance will"
#Generator text
result=generator (prompt, max_length=50, num_return_sequences=1)
print("AI Generator text:")
print(result[0]['generated_text'])

