# -*- coding: utf-8 -*-
"""Timetable generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j-hyJ4nGjWU3m6zxmq3VD33aNAVkqYG_
"""

import pandas as pd
import random

print("TIMETABLE GENERATOR\n")

# User Input
subjects_input = input("Enter subjects (comma separeted):")
days_input = input("Enter daysm(comma separated):")
periods_per_day = int(input("Enter num of periods per day:"))

# Process Input
subjects = [s.strip()for s in subjects_input.split(",") if s.strip()]
days = [d.strip() for d in days_input.split(",") if d.strip()]

# Validation
if len(subjects) == 0 or len(days) == 0 or periods_per_day <= 0:
  print("Invalid input. please try again.")
else:
  timetable = {}

  for day in days:
    timetable[day] = random.choices(subjects, k=periods_per_day)

    # Create DataFrame
    df = pd.DataFrame(timetable)
    df.index = [f"period {i+1}" for i in range(periods_per_day)]

    print('\nTimetable Generated successfully\n')
    display(df)

  # Save timetable
  df.to_csv("timetable.csv")
  print("\nTimetable saved as timetable.CSV")